export const GENRES = [
  "Acoustic",
  "Alternative",
  "Ambient/Meditation",
  "Americana",
  "Bluegrass",
  "Blues",
  "Christian/Gospel",
  "Christian Contemporary",
  "Celtic/Irish",
  "Classic Rock",
  "Classical",
  "Comedy",
  "Country",
  "Cover/Tribute",
  "Dance/EDM",
  "Disco",
  "DJ",
  "Drum & Bass",
  "Dubstep",
  "Electronic",
  "Folk",
  "Funk",
  "House",
  "Indie",
  "Industrial",
  "Instrumental",
  "Jam",
  "Jazz",
  "Kids/Family",
  "Latin",
  "Lounge",
  "Metal",
  "New Age",
  "Opera",
  "Pop",
  "Progressive",
  "Psychedelic",
  "Punk",
  "R&B/Soul",
  "Rap/Hip-Hop",
  "Reggae/Ska",
  "Rock",
  "Shoegaze",
  "Singer/Songwriter",
  "Soundtrack",
  "Techno",
  "Trance/Psytrance",
  "Trap",
  "Triphop",
  "Vocal",
  "World"
];
