// USER
export const REGISTER_USER = "REGISTER_USER";
export const VERIFY_USER_EMAIL = "VERIFY_USER";
export const GET_CURRENT_USER = "GET_CURRENT_USER";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const SET_LOGOUT_PENDING = "SET_LOGOUT_PENDING";
export const SET_LOGIN_PENDING = "SET_LOGIN_PENDING";
export const SET_AUTHENTICATED = "SET_AUTHENTICATED";

export const GET_PROFILE_PENDING = "GET_PROFILE_PENDING";
export const SAVE_PROFILE_PENDING = "SAVE_PROFILE_PENDING";
export const SET_PROFILE = "SET_PROFILE";

export const GET_BAND_PENDING = "GET_BAND_PENDING";
export const SAVE_BAND_PENDING = "SAVE_BAND_PENDING";
export const SET_BAND = "SET_BAND";

export const SET_REGISTER_PENDING = "SET_REGISTER_PENDING";
export const SET_REGISTER_STATUS = "SET_REGISTER_STATUS";

export const SET_VERIFY_PENDING = "SET_VERIFY_PENDING";
export const SET_VERIFY_STATUS = "SET_VERIFY_STATUS";

export const ERROR = "ERROR";
export const SUCCESS = "SUCCESS";

export const SEND_MESSAGE = "SEND_MESSAGE";
export const REMOVE_MESSAGE = "REMOVE_MESSAGE";

export const SEND_NOTIFICATION = "SEND_NOTIFICATION";
export const REMOVE_NOTIFICATION = "REMOVE_NOTIFICATION";
