// USER
export const GET_CURRENT_USER = 'GET_CURRENT_USER';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const LOGGING_IN = 'LOGGING_IN';

export const SET_LOGOUT_PENDING = 'SET_LOGOUT_PENDING';
export const SET_LOGIN_PENDING = 'SET_LOGIN_PENDING';
export const SET_AUTH_STATUS = 'SET_AUTH_STATUS';
export const SET_AUTH_ERROR = 'SET_AUTH_ERROR';
